name: VCommandParser
version: '${project.version}'
main: com.vihncraft.libs.vcommandparser.VCommandParser
api-version: '1.20'
load: STARTUP
description: 'A free and open source command parsing library for Paper, orignally designed for use on the VihnCraft Minecraft Server.'
website: 'https://github.com/VihnCraft/VCommandParser'
authors:
  - 'AlignedCookie88'
permissions:
  vcommandparser.admin:
    description: 'Admin commands for VCommandParser'
commands:
  vcommandparser:
    permission: vcommandparser.admin
